#!/bin/sh

export PANEL_HEIGHT=25
export GAP=10

# remove gaps from edes
bspc config window_gap $GAP
bspc config top_padding $(($PANEL_HEIGHT - $GAP))
bspc config left_padding -$GAP
bspc config right_padding -$GAP
bspc config bottom_padding -$GAP

bspc monitor -d I II III IV V VI VII VIII IX X
bspc config border_width 2
bspc config window_gap $GAP
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config paddinless_monocle false
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config honor_size_hints true
bspc config focused_border_color "#1ABB9B"
bspc config normal_border_color "#222D32"
bspc config presel_border_color "#1ABB9B"
bspc config border_width 1
#bspc config focus_follows_pointer = true

