theme = "monokai"

[editor]
bufferline = "always" # tab bar at top
color-modes = true
# line-number = "relative"
mouse = true
rulers = [80, 100]
scrolloff = 8
soft-wrap.enable = true

[editor.auto-save]
focus-lost = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
display-signature-help-docs = true
snippets = false

[keys.normal]
C-right = "move_next_word_end"
C-left = "move_prev_word_start"
"#" = "toggle_comments"

[keys.insert]
C-right = ["move_next_word_end", "move_char_right"]
C-left = ["move_prev_word_start"]
