theme = "monokai"

[editor]
line-number = "relative"
rulers = [80]
scrolloff = 8

[editor.auto-save]
focus-lost = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
snippets = false
